### ISSUE TITLE
Write README

### ISSUE THREAD

**Issue by jatinkatyal13** [coding-blocks/poker#1]
The idea behind this project is to create an application that makes an Http request periodically on the given endpoint. This will give us more control rather than using crontab or agendajs.

Task: Write a README explaining the project and the installation step

README should include following things:
- [ ] Heading of the project
- [ ] Project explanation
- [ ] Minimum python version requirement (3.6)
- [ ] Setting pipenv in python
- [ ] Installing dependencies using pipenv
- [ ] Running the Django project
- [ ] Explaining Project structure
- [ ] Building the Docker container
- [ ] Running the application as a Docker container using docker-compose

**Comment by tushargoyal22** [comment]
Hi, I would like to do this task

**Comment by jatinkatyal13** [comment]
@tushargoyal22 sure! all the best 🚀

**Comment by Anupam-USP** [comment]
Sir is it open till now? It seems that I can work on this.

**Comment by jatinkatyal13** [comment]
Sure you can start working on it and make sure to tag the issue in your pull request!

**Comment by tushargoyal22** [comment]
As I can see, in Pipfile the python version required is 3.6 so I installed pyenv package which allows the installation of the required python version as in Pipfile if that is already not there in the system. pyenv package is also not helping. Sir, can u please help a bit
![Screenshot from 2020-05-10 21-51-21](https://user-images.githubusercontent.com/43175862/81523088-66e01780-936a-11ea-841e-0d727ed560e9.png)

**Comment by jatinkatyal13** [comment]
@tushargoyal22 thanks for informing 🚀 ! **I've fixed this issue** and since Pipfile doesn't support multiple python version as required we can specify it in our README

**Comment by tushargoyal22** [comment]
thanks i was struggling for entire night yesterday in this but it helped me understanding about so many packages :)

**Comment by NeerajSirvisetti** [comment]
@jatinkatyal13 Sir I want to contribute too, but as a beginner how Can I understand and contribute to the project, sir?

**Comment by tushargoyal22** [comment]
u can read about Django framework official documentation

**Comment by tushargoyal22** [comment]
> @jatinkatyal13 Sir I want to contribute too, but as a beginner how Can I understand and contribute to the project, sir?

u can read about Django framework official documentation

**Comment by prateek2211** [comment]
@jatinkatyal13 I have created a PR. Please have a look

**Comment by saphal1998** [comment]
Hi, can someone post their directory structure? I think I am not putting the .env file in the right place. It should be on the same level as the manage.py file right? @jatinkatyal13 

Since you guys have already set this up @prateek2211 @tushargoyal22 Can you help me out with this?

**Comment by tushargoyal22** [comment]
> Hi, can someone post their directory structure? I think I am not putting the .env file in the right place. It should be on the same level as the manage.py file right? @jatinkatyal13
> 
> Since you guys have already set this up @prateek2211 @tushargoyal22 Can you help me out with this?

sample .env file named as .env.sample is already at the same level as manage.py . can u elaborate ur concern.

**Comment by saphal1998** [comment]
This is my directory structure
<img width="259" alt="Screenshot 2020-05-12 at 1 47 15 PM" src="https://user-images.githubusercontent.com/31125345/81659201-1f838500-9457-11ea-9abc-e3565afc70b9.png">

This is my .env file

<img width="324" alt="Screenshot 2020-05-12 at 1 49 05 PM" src="https://user-images.githubusercontent.com/31125345/81659444-59548b80-9457-11ea-9c44-9609cb34dcc7.png">

Upon running migrate, it keeps throwing errors that I think are related to the database, as it says that no host named 'postgres' was found, inspite of me having defined DB_HOST = localhost
So I think the decouple library is not able to get my config properly, I think it is because I am placing the file in an incorrect location.

**Comment by prateek2211** [comment]
are your username and password correct?

did you even setup local postgres?

**Comment by jatinkatyal13** [comment]
@saphal1998 I'm using DB_HOST=postgres because this refers to domain name of postgres container when the application is ran as docker. You need not install postgres and run it as a standalone container. Follow [this](https://hackernoon.com/dont-install-postgres-docker-pull-postgres-bee20e200198) guide for help.

**Comment by saphal1998** [comment]
> are your username and password correct?
> 
> did you even setup local postgres?

Yes they are, I did create the database as well as the user. The problem seemed to be the host. Using Docker it works now, thanks for the help!

**Comment by tushargoyal22** [comment]
@jatinkatyal13  as told by @saphal1998  there is some issue with the hostname of DB.  I tried to run without docker, directly, its saying
`django.db.utils.OperationalError: could not translate host name "localhost" to address: Temporary failure in name resolution
`
I tried DB_HOST = postgres as well but it lead to same error when I run the application. Can u please explain this DB_HOST

**Comment by jatinkatyal13** [comment]
It is simply the variable which represents the database host. In production it'll be an actual link, in dev, it should be either localhost or 127.0.0.1, inside docker it can be the name of the db container

**Comment by MidhaShrey** [comment]
sir i would like to work upon this issue

**Comment by gauthampkrishnan** [comment]
Sir I would look to work for this issue can you please assign me?

**Comment by chandresh189** [comment]
Sir i would like to work on this sood first issue
