### ISSUE TITLE
Add monitoring pages

### ISSUE THREAD

**Issue by jatinkatyal13** [coding-blocks/poker#16]
Currently, all the actions in the Application are controlled using the Django Admin Panel but we need views where we can monitor the application for new logs and check the response from the server. 

While creating templates please follow the practices in the current setup
- Layouts go in the root of the templates folder.
- Each application's templates are in their separate folder.
- Each application will have its own partials folder.

While creating Views please follow these practices
- Try using class-based views wherever possible.
- Don't use `View` if the customization can be done using mixins.
- Create a folder named `views` inside the cron application which have following folders.
    - `pages` - This will contain all the views which we will be working on in this issue
    - `api` - This will contain all the views which we will be working on in the upcoming issue. (For now just add a `.gitkeep` file in this folder
    - Inside each folder add a `views.py` and `urls.py`

- [ ] Create View's folder structure
- [ ] Implement Page Views
    - [ ] Application list page view with pagination - `/applications`
    - [ ] Application list page template
    - [ ] Application detail view which lists all the jobs paginated - `/applications/<id>`
    - [ ] Application detail view template
    - [ ] Jobs detail view which lists all the logs paginated - `/jobs/<id>`
    - [ ] Jobs detail view template
        - [ ] Should have an execute now button
        - [ ] Can apply filter on Logs ( status, created_at )
- [ ] Test the application locally and attach screenshots while making the final submission.

**Comment by jatinkatyal13** [comment]
![6d2b14c53a164ceaabfd9e8a19bfecbf](https://user-images.githubusercontent.com/18536540/82752666-3625c680-9ddd-11ea-90f0-315946e41c78.png)
These wireframes for the pages might help although you can add more features if you want

**Comment by prateek2211** [comment]
> Each application's templates are in their separate folder.

You mean, a template folder inside application like
```
-cron
  -templates
     -cron
```
Am I right?
@jatinkatyal13

**Comment by jatinkatyal13** [comment]
What I mean is something like
- templates
    - cron
        - index.html
    - oneauth
        - index.html

You will need to move the oneauth application templates as well
