### ISSUE TITLE
Setup authentication using oneauth

### ISSUE THREAD

**Issue by jatinkatyal13** [coding-blocks/poker#2]
Currently, the project uses Django authentication mechanism but we need to authenticate users via our SSO platform [oneauth](https://account.codingblocks.com) 

To get started with this task:
1. I'll recommend you to read about the authentication flow in OAuth 2.0. You refer [this](https://www.digitalocean.com/community/tutorials/an-introduction-to-oauth-2) article.
2. Go to https://account.codingblocks.com and create a new Client under My Clients tab
    - Use localhost:8000 as the callback url and default url
3.  Create two vars in `settings.py` file `ONEAUTH_CLIENT_ID` and `ONEAUTH_CLIENT_SECRET` whose values are fetched from the .env file

ToDos for the task are:
- [ ] Replace `LOGIN_URL` in the `settings.py` with the authorization URL of oneauth
- [ ] Create a new application named `oneauth` and an endpoint which handles the callback from oneauth
- [ ] Exchange grant code with the access token
- [ ] Use access token to retrieve the user detail from the oneauth using `/api/users/me` endpoint
- [ ] Upsert user from the database
    - Use email id to fetch the user from database
        - [ ] If user exists update the user details and log in the user
        - [ ] If user doesn't extsts create the user and log in

**Comment by prateek2211** [comment]
I would like to work on this

**Comment by tushargoyal22** [comment]
i would also like to work on this
