### ISSUE TITLE
Generate Logs

### ISSUE THREAD

**Issue by jatinkatyal13** [coding-blocks/poker#3]
Currently, the request is sent using `scrips/request_curl.py` file which is set in the environment path inside the docker container as written [here](https://github.com/coding-blocks/poker/blob/master/Dockerfile#L15). 

Edit the `request_curl.py` to generate the logs after sending the request containing the status code and response from the server. To access the models inside the request_curl, Django's settings.py must be instantiated. You can refer [this](https://docs.djangoproject.com/en/3.0/howto/custom-management-commands/) link to create a custom Django admin command and execute it.

Since the crontab runs all the command from the home(~) directory of the user you'll need to Change Directory before executing the script [here](https://github.com/coding-blocks/poker/blob/master/services/crontab.py#L12)

**Comment by Syn3rman** [comment]
Hey @jatinkatyal13,

I'd like to work on this if it is available, mind if I take it?
Also, are the contributions counted only if they are made after 15th of this month?

Thanks!

**Comment by prateek2211** [comment]
Is someone working on this? I would be glad to work on this.

**Comment by Syn3rman** [comment]
Hey @prateek2211,

I'm working on this. There's just one thing that I don't understand about this - why don't we use the logging package to log the messages to the logfile?
Something along the lines:

```
logger = logging.getLogger('poker')
hdlr = logging.FileHandler('/var/tmp/poker.log')
formatter = logging.Formatter('%(asctime)s %(levelname)s %(message)s')
hdlr.setFormatter(formatter)
logger.addHandler(hdlr) 
logger.setLevel(logging.WARNING)

formatted_res = f"Response status code: {res.status_code}; body: {res.json}"
logger.info(formatted_res)
```
Could you help me out here @jatinkatyal13?

**Comment by jatinkatyal13** [comment]
The logs that we are trying to generate are not application logs but the request log. These will be used to monitor the requests sent and whether they were successful or not. 

With Django models we will be able to support filtering and analytics

**Comment by sensei23** [comment]
Hi
I am contributing to BOSS for the first time and I'd like to work on this but i have a few doubts: -
1. Why do we require "create a custom Django admin command and execute it" this, aren't we logging the requests in the Log Model which is in the cron App. 
2. Why are we changing the working directory?

can someone please help?

**Comment by prateek2211** [comment]
Hmm, I am not quite aware of how the issues assignment work here. Is it ok for someone to work on an issue if issue is claimed by someone else (though not assigned), like here.

I mean would it be fine if I also work on this when someone else has already commented
@jatinkatyal13

**Comment by jatinkatyal13** [comment]
@prateek2211 You can start working on it and the best PR will be merged

**Comment by jatinkatyal13** [comment]
> Hi
> I am contributing to BOSS for the first time and I'd like to work on this but i have a few doubts: -
> 
> 1. Why do we require "create a custom Django admin command and execute it" this, aren't we logging the requests in the Log Model which is in the cron App.
> 2. Why are we changing the working directory?
> 
> can someone please help?

The logs are generated outside Django application in the crontab

**Comment by prateek2211** [comment]
@jatinkatyal13 Please correct me if I am wrong: Basically we have to create a custom management command to send request, which could be called like `python manage.py sendrequest` and use this instead of script

**Comment by jatinkatyal13** [comment]
@prateek2211 Correct

**Comment by prateek2211** [comment]
@jatinkatyal13 How would we pass `Job` while creating a `Log`, because the only things we pass to script are url, token and method (which does not necessarily give a single Job object). Possible way could be to pass job_id to script, or
add unique constraint to url, method, and token

**Comment by jatinkatyal13** [comment]
@prateek2211 adding the job_id as the parameter seems a good option. We will be having the Django setting context and hence can fetch the instance from the DB

**Comment by prateek2211** [comment]
@jatinkatyal13 I have created a PR, please see if it's what you were looking for
