### ISSUE TITLE
Add nginx

### ISSUE THREAD

**Issue by jatinkatyal13** [coding-blocks/poker#8]
Currently, we serve our application directly by exposing the gunicorn from our container. Due to this, we are not able to serve our static file as Django doesn't support and recommend serving static files in production on its own. We need to use services like apache or nginx.

- [ ] Install Nginx inside the container
- [ ] Create `nginx.conf`
    - [ ] Serve static file under tha url written in `settings.py`
    - [ ] proxy pass rest of the request to the gunicorn running on port 8000
- [ ] update entrypoint script
    - [ ] enable our nginx conf
    - [ ] run collect static before spinning up the server

**Comment by rahljoshi** [comment]
can I give it a try

**Comment by jatinkatyal13** [comment]
Sure! @mrjoshi0147
